# Generated by Django 2.0.5 on 2018-11-11 03:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_id', models.IntegerField(default=0)),
                ('individuating_trait', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('source', models.IntegerField()),
                ('target', models.IntegerField()),
                ('value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.IntegerField(default=0)),
                ('measurement_name', models.CharField(max_length=100)),
                ('measurement_display_name', models.CharField(max_length=300)),
                ('measurement_desc', models.CharField(max_length=600)),
                ('measurement_stature', models.BooleanField(default=False)),
                ('measurement_sex', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('sb_id', models.IntegerField()),
                ('se_side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('MIDDLE', 'Middle'), ('UNSIDED', 'Unsided')], default='', max_length=20)),
                ('completeness', models.CharField(choices=[('COMPLETE', 'Complete'), ('MC', 'Mostly complete'), ('PARTIAL', 'Partial')], default='', max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('FLAT', 'flat'), ('IRREGULAR', 'irregular'), ('LONG', 'long bone'), ('SHORT', 'short bone'), ('TOOTH', 'tooth'), ('N/A', 'not available')], default='', max_length=12)),
                ('group', models.CharField(choices=[('AP', 'Appendicular'), ('AX', 'Axial'), ('N/A', 'Not available'), ('Toot', 'Tooth')], default='', max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('paired', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=6)),
                ('articulated', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathology_id', models.IntegerField(default=0)),
                ('abnormality_category', models.CharField(max_length=30)),
                ('pathology_characteristics', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Sb_art',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=20)),
                ('name', models.CharField(default='', max_length=20)),
                ('category', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeAnomaly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SeArticulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulation_id', models.IntegerField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SeMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_id', models.IntegerField()),
                ('measure', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SkeletalBones',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('FLAT', 'flat'), ('IRREGULAR', 'irregular'), ('LONG', 'long bone'), ('SHORT', 'short bone'), ('TOOTH', 'tooth'), ('N/A', 'not available')], default='', max_length=12)),
                ('group', models.CharField(choices=[('AP', 'Appendicular'), ('AX', 'Axial'), ('N/A', 'Not available'), ('Toot', 'Tooth')], default='', max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('paired', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=6)),
                ('articulated', models.BooleanField(choices=[('TRUE', True), ('FALSE', False)], max_length=6)),
                ('sb_zones', models.BooleanField(choices=[('TRUE', True), ('FALSE', False)], default=False, max_length=6)),
                ('sb_measurements', models.BooleanField(choices=[('TRUE', True), ('FALSE', False)], default=False, max_length=6)),
                ('dental', models.BooleanField(choices=[('TRUE', True), ('FALSE', False)], default=False, max_length=6)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SkeletalElement',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=150)),
                ('accession_number', models.CharField(max_length=100)),
                ('g_number', models.CharField(max_length=50)),
                ('x_number', models.CharField(max_length=30)),
                ('designator', models.IntegerField(default=0)),
                ('se_side', models.CharField(choices=[('LEFT', 'Left'), ('RIGHT', 'Right'), ('MIDDLE', 'Middle'), ('UNSIDED', 'Unsided')], default='', max_length=10)),
                ('completeness', models.CharField(choices=[('COMPLETE', 'Complete'), ('MC', 'Mostly complete'), ('PARTIAL', 'Partial')], default='', max_length=20)),
                ('measured', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('dna_sampled', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('ct_scanned', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('xray_scanned', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('clavicle_triage', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('inventoried', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('reviewed', models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10)),
                ('sb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalBones')),
            ],
        ),
        migrations.CreateModel(
            name='Taphonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taphonomy_id', models.IntegerField(default=0)),
                ('taphonomy_branch', models.CharField(max_length=20)),
                ('taphonomy_name', models.CharField(max_length=50)),
                ('taphonomy_category', models.CharField(max_length=100)),
                ('taphonomy_type', models.CharField(max_length=50)),
                ('taphonomy_subtype', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trauma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trauma_id', models.IntegerField(default=0)),
                ('trauma_timing', models.CharField(choices=[('ANTE', 'Antemortem'), ('PERI', 'Perimortem')], default='', max_length=20)),
                ('trauma_type', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.IntegerField(default=0)),
                ('zone_name', models.IntegerField(default='')),
                ('zone_description', models.CharField(max_length=120)),
                ('zone_sb_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalBones')),
            ],
        ),
        migrations.AddField(
            model_name='semeasurement',
            name='measure_se_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalElement'),
        ),
        migrations.AddField(
            model_name='searticulation',
            name='articulation_se_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalElement'),
        ),
        migrations.AddField(
            model_name='seanomaly',
            name='anomaly_se_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalElement'),
        ),
        migrations.AddField(
            model_name='measurements',
            name='measurement_bone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalBones'),
        ),
        migrations.AddField(
            model_name='anomalys',
            name='anomaly_bone_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coraapp.SkeletalBones'),
        ),
    ]
