# Generated by Django 2.0.5 on 2018-11-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coraapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodes',
            name='articulated',
            field=models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='paired',
            field=models.CharField(choices=[('TRUE', True), ('FALSE', False)], max_length=10),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='type',
            field=models.CharField(choices=[('FLAT', 'flat'), ('IRREGULAR', 'irregular'), ('LONG', 'long bone'), ('SHORT', 'short bone'), ('TOOTH', 'tooth'), ('N/A', 'not available')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='sb_art',
            name='category',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='sb_art',
            name='group_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='sb_art',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='skeletalbones',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='skeletalelement',
            name='g_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skeletalelement',
            name='x_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='taphonomy',
            name='taphonomy_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='trauma_timing',
            field=models.CharField(choices=[('ANTE', 'Antemortem'), ('PERI', 'Perimortem')], default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='trauma',
            name='trauma_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
